


/* Products list */

const products = [
    { id: 1, name: "Apple iPhone 13 (128 GB, 256 GB, 512 GB)", price: "40,999" , category: "13" , imageUrl: 'images/13-1.png', des: "Dual 12MP Camera System (Wide and Ultra Wide), Wide: f/1.6 Aperture, Ultra Wide: f/2.4 Aperture, 120 Degree FOV, 2x Optical Zoom out, Digital Zoom up to 5x, Portrait Mode with Advanced Bokeh and Depth Control, Portrait Lighting with Six Effects (Natural, Studio, Contour, Stage, Stage Mono, High‑Key Mono), Sensor-shift Optical Image Stabilisation (Wide), Seven‑element Lens (Wide), Five‑element Lens (Ultra Wide), Panorama (up to 63MP), Sapphire Crystal Lens Cover, 100% Focus Pixels (Wide), Night Mode Deep Fusion, Smart HDR 4, Photographic Styles, Wide Colour Capture for Photos and Live Photos, Lens Correction (Ultra Wide), Advanced Red‑eye Correction, Auto Image Stabilisation, Burst Mode, Photo Geotagging, Image Formats Captured: HEIF and JPEG, Video Recording: Sensor-shift OIS for Video (Wide), Audio Zoom, QuickTake Video, Time‑lapse Video with Stabilisation, Night Mode Time-lapse, Cinematic Video Stabilisation (4K, 1080p and 720p), Continuous AF Video, Playback Zoom, Stereo Recording" },

    { id: 2, name: "Apple iPhone 14 (128 GB, 256 GB, 512 GB)", category: "14", price: "50,999", imageUrl: 'images/14.1.png', des: "Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC Standard 60529, 16 Core Neural Engine, Enabled by TrueDepth Camera for Facial Recognition, Emergency SOS, Crash Detection, Digital Compass, Wi-Fi, Cellular, iBeacon Micro-Location, FaceTime Video Calling Over Cellular or Wi-Fi, FaceTime HD (1080p) Video Calling Over 5G or Wi-Fi, Share Experiences Like Movies, TV, Music and Other Apps in a FaceTime Call with SharePlay, Screen Sharing, Portrait Mode in FaceTime Video, Spatial Audio, Voice Isolation and Wide Spectrum, Microphone Modes, Zoom with Rear-Facing Camera, FaceTime Audio, Voice over LTE (VoLTE), Wi-Fi Calling, Spatial Audio Playback, User Configurable Maximum Volume Limit, HDR with Dolby Vision, HDR10 and HLG Upto 4K HDR AirPlay for Mirroring, Photos and Video Out to Apple TV (2nd generation or later) or AirPlay 2 Enabled Smart TV, Video Mirroring and Video Out Support: Upto 1080p Through Lightning Digital AV Adapter and Lightning to VGA Adapter (Adapters Sold Separately), MagSafe Wireless Charging Upto 15 W, Qi Wireless Charging Upto 7.5 W, Charging via USB to Computer System or Power Adapter, Magnet Array, Voice Control, Voice Over, Zoom, Magnifier, RTT and TTY Support, Siri and Dictation, Type to Siri, Switch Control, Closed Captions, Assistive Touch, Spoken Content, Back Tap, Alignment Magnet, Accessory Identification NFC, Magnetometer, System Requirement: Apple ID (Required for Some Features), Internet Access, Syncing to a Mac or PC Requires: macOS Catalina 10.15 or Later Using the Finder, macOS El Capitan 10.11.6 Through macOS Mojave 10.14.6 Using iTunes 12.8 or Later, Windows 7 or Later Using iTunes 12.10.10 or Later (Free Download from apple.com/in/itunes/download), Rating for Hearing Aids: M3, T4" },

    { id: 3, name: "Apple iPhone 15 (128 GB, 256 GB, 512 GB)", category: "15" , price: "54,999", imageUrl: 'images/15.1.png', des: "Aluminium Design, Ceramic Shield Front, Colour Infused Glass Back, Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC Standard 60529, 16 Core Neural Engine, Enabled by TrueDepth Camera for Facial Recognition, Apple Pay, Emergency SOS via Satellite, Crash Detection, 5G (sub 6 GHz) with 4x4 MIMO, Gigabit LTE with 4x4 MIMO and LAA, 2x2 MIMO, Second Generation Ultra Wideband Chip, NFC with Reader Mode, Express Cards with Power Reserve, FaceTime Video Calling Over Wi Fi or a Mobile Network, FaceTime HD (1080p) Video Calling Over 5G or Wi Fi, Share Experiences like Movies, TV, Music and Other Apps in a FaceTime Call with SharePlay, Screen Sharing, Portrait Mode in FaceTime Video, Spatial Audio, Voice Isolation and Wide Spectrum Microphone Modes, Zoom with Rear Facing Camera, FaceTime Audio, Voice Over LTE (VoLTE), Wi Fi Calling, Spatial Audio, Voice Isolation and Wide Spectrum Microphone Modes, Spatial Audio Playback, User Configurable Maximum Volume Limit, Supported Formats Include HEVC, H.264 and ProRes, HDR with Dolby Vision, HDR10 and HLG, Upto 4K HDR AirPlay for Mirroring, Photos and Video Out to Apple TV (2nd Generation or Later) or AirPlay Enabled Smart TV, Video Mirroring and Video Out Support: Upto 4K HDR through Native DisplayPort Output Over USB-C or USB C Digital AV Adapter (Model A2119, Adapter Sold Separately), USB-C Connector with Support For: Charging, DisplayPort, USB 2 (Upto 480Mb/s), Built-in Rechargeable Lithium-ion Battery, MagSafe Wireless Charging Upto 15W, Qi Wireless Charging Upto 7.5W, Fast Charge Capable: Upto 50% Charge in Around 30 Minutes with 20W Adapter or Higher (Available Separately), MagSafe: Magnet Array, Alignment Magnet, Accessory Identification NFC, Magnetometer, VoiceOver, Zoom, Magnifier, Accessibility: Voice Control, Switch Control, AssistiveTouch, RTT and Textphone Support, Closed Captions, Live Captions, Personal Voice, Live Speech, Type to Siri, Spoken Content, Rating for Hearing Aids: M3, T4, System Requirements: Apple ID (Required for Some Features), Internet Access, Syncing to a Mac or PC Requires: macOS Catalina 10.15 or Later Using the Finder, macOS High Sierra 10.13 to macOS Mojave 10.14.6 Using iTunes 12.9 or Later, Windows 10 or Later Using iTunes 12.12.10 or Later (Free Download From itunes.com/uk)" },

    { id: 4, name: "Apple iPhone 16 (128 GB, 256 GB, 512 GB)", category: "16", price: "79,990", imageUrl: 'images/16.1.png',des: "Aluminium Design, Ceramic Shield Front, Colour Infused Glass Back, Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC Standard 60529, 16 Core Neural Engine, Enabled by TrueDepth Camera for Facial Recognition, Apple Pay, Emergency SOS via Satellite, Crash Detection, 5G (sub 6 GHz) with 4x4 MIMO, Gigabit LTE with 4x4 MIMO and LAA, 2x2 MIMO, Second Generation Ultra Wideband Chip, NFC with Reader Mode, Express Cards with Power Reserve, FaceTime Video Calling Over Wi Fi or a Mobile Network, FaceTime HD (1080p) Video Calling Over 5G or Wi Fi, Share Experiences like Movies, TV, Music and Other Apps in a FaceTime Call with SharePlay, Screen Sharing, Portrait Mode in FaceTime Video, Spatial Audio, Voice Isolation and Wide Spectrum Microphone Modes, Zoom with Rear Facing Camera, FaceTime Audio, Voice Over LTE (VoLTE), Wi Fi Calling, Spatial Audio, Voice Isolation and Wide Spectrum Microphone Modes, Spatial Audio Playback, User Configurable Maximum Volume Limit, Supported Formats Include HEVC, H.264 and ProRes, HDR with Dolby Vision, HDR10 and HLG, Upto 4K HDR AirPlay for Mirroring, Photos and Video Out to Apple TV (2nd Generation or Later) or AirPlay Enabled Smart TV, Video Mirroring and Video Out Support: Upto 4K HDR through Native DisplayPort Output Over USB-C or USB C Digital AV Adapter (Model A2119, Adapter Sold Separately), USB-C Connector with Support For: Charging, DisplayPort, USB 2 (Upto 480Mb/s), Built-in Rechargeable Lithium-ion Battery, MagSafe Wireless Charging Upto 15W, Qi Wireless Charging Upto 7.5W, Fast Charge Capable: Upto 50% Charge in Around 30 Minutes with 20W Adapter or Higher (Available Separately), MagSafe: Magnet Array, Alignment Magnet, Accessory Identification NFC, Magnetometer, VoiceOver, Zoom, Magnifier, Accessibility: Voice Control, Switch Control, AssistiveTouch, RTT and Textphone Support, Closed Captions, Live Captions, Personal Voice, Live Speech, Type to Siri, Spoken Content, Rating for Hearing Aids: M3, T4, System Requirements: Apple ID (Required for Some Features), Internet Access, Syncing to a Mac or PC Requires: macOS Catalina 10.15 or Later Using the Finder, macOS High Sierra 10.13 to macOS Mojave 10.14.6 Using iTunes 12.9 or Later, Windows 10 or Later Using iTunes 12.12.10 or Later (Free Download From itunes.com/uk)"},

    { id: 5, name: "Apple iPhone 13 Pro (128 GB, 256 GB, 512 GB)", category: "13",price: "1,19,900", imageUrl: 'images/13pro.1.png', des: "Pro 12MP Camera System (Telephoto, Wide and Ultra Wide), Telephoto: f/2.8 Aperture, Wide: f/1.5 Aperture, Ultra Wide: f/1.8 Aperture, 120 Degree FOV, 3x Optical Zoom In, 2x Optical Zoom out, 6x Optical Zoom Range, Digital Zoom up to 15x, Night Mode Portraits Enabled by LiDAR Scanner, Portrait Mode with Advanced Bokeh and Depth Control, Portrait Lighting with Six Effects (Natural, Studio, Contour, Stage, Stage Mono, High‑Key Mono), Dual Optical Image Stabilisation (Telephoto and Wide), Sensor‑shift Optical Image Stabilisation (Wide), Six‑element Lens (Telephoto and Ultra Wide), Seven‑element Lens (Wide), Panorama (up to 63MP), 100% Focus Pixels (Wide), Night Mode, Deep Fusion, Smart HDR 4, Photographic Styles, Macro Photography, Apple ProRAW, Wide Colour Capture for Photos and Live Photos, Lens Correction (Ultra Wide), Advanced Red‑eye Correction, Photo Geotagging, Auto Image Stab" },
    { id: 6, name: "Apple iPhone 14 Pro (128 GB, 256 GB, 512 GB)", category: "14",price: "1,19,900", imageUrl: 'images/14.1.png', des: "Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC Standard 60529, 16 Core Neural Engine, Enabled by TrueDepth Camera for Facial Recognition, Emergency SOS, Crash Detection, Digital Compass, Wi-Fi, Cellular, iBeacon Micro-Location, FaceTime Video Calling Over Cellular or Wi-Fi, FaceTime HD (1080p) Video Calling Over 5G or Wi-Fi, Share Experiences Like Movies, TV, Music and Other Apps in a FaceTime Call with SharePlay, Screen Sharing, Portrait Mode in FaceTime Video, Spatial Audio, Voice Isolation and Wide Spectrum, Microphone Modes, Zoom with Rear-Facing Camera, FaceTime Audio, Voice over LTE (VoLTE), Wi-Fi Calling, Spatial Audio Playback, User Configurable Maximum Volume Limit, HDR with Dolby Vision, HDR10 and HLG Upto 4K HDR AirPlay for Mirroring, Photos and Video Out to Apple TV (2nd generation or later) or AirPlay 2 Enabled Smart TV, Video Mirroring and Video Out Support: Upto 1080p Through Lightning Digital AV Adapter and Lightning to VGA Adapter (Adapters Sold Separately), MagSafe Wireless Charging Upto 15 W, Qi Wireless Charging Upto 7.5 W, Charging via USB to Computer System or Power Adapter, Magnet Array, Voice Control, Voice Over, Zoom, Magnifier, RTT and TTY Support, Siri and Dictation, Type to Siri, Switch Control, Closed Captions, Assistive Touch, Spoken Content, Back Tap, Alignment Magnet, Accessory Identification NFC, Magnetometer, System Requirement: Apple ID (Required for Some Features), Internet Access, Syncing to a Mac or PC Requires: macOS Catalina 10.15 or Later Using the Finder, macOS El Capitan 10.11.6 Through macOS Mojave 10.14.6 Using iTunes 12.8 or Later, Windows 7 or Later Using iTunes 12.10.10 or Later (Free Download from apple.com/in/itunes/download), Rating for Hearing Aids: M3, T4" },

    { id: 7, name: "Apple iPhone 15 Pro  (128 GB, 256 GB, 512 GB)", category: "15",price: "1,19,999", imageUrl: 'images/15pro.1.png' , des: "Titanium Design, Ceramic Shield Front, Textured Matt Glass Back, Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC standard 60529, New 16 Core Neural Engine, Enabled by TrueDepth Camera for Facial Recognition, Apple Pay, Emergency SOS via Satellite, Crash Detection, 5G (sub 6 GHz) with 4x4 MIMO, Gigabit LTE with 4x4 MIMO and LAA, 2x2 MIMO, Second Generation Ultra Wideband Chip, Thread Networking Technology, NFC with Reader Mode, Express Cards with Power Reserve, FaceTime Video Calling Over Wi Fi or a Mobile Network, FaceTime HD (1080p) Video Calling Over 5G or Wi Fi, Share Experiences Like Movies, TV, Music and Other Apps in a FaceTime Call With SharePlay, Screen Sharing, Portrait Mode in FaceTime Video, Spatial Audio, Voice Isolation and Wide Spectrum Microphone Modes, Optical Zoom with Rear Facing Camera, FaceTime Audio, Voice Over LTE (VoLTE), Wi Fi Calling, Spatial Audio Playback, User Configurable Maximum Volume Limit, Supported Formats Include HEVC, H.264 and ProRes, HDR with Dolby Vision, HDR10 and HLG, Upto 4K HDR AirPlay for Mirroring, Photos and Video Out to Apple TV (2nd Generation or Later) or AirPlay Enabled Smart TV, Video Mirroring and Video Out Support: Upto 4K HDR Through Native DisplayPort Output Over USB-C or USB-C Digital AV Adapter (Model A2119, Adapter Sold Separately), USB C Connector with Support For: Charging, DisplayPort, USB 3 (Upto 10Gb/s), Built-in Rechargeable Lithium ion Battery, MagSafe Wireless Charging Upto 15W, Qi wireless Charging Upto 7.5W, Fast Charge Capable: Upto 50% Charge in around 30 Minutes, With 20W Adapter or Higher (Available Separately), MagSafe: Magnet Array, Alignment Magnet, Accessory Identification NFC, Magnetometer, Accessibility: VoiceOver, Zoom, Magnifier, Voice Control, Switch Control, AssistiveTouch, RTT and Textphone Support, Closed Captions, Live Captions, Personal Voice, Live Speech, Type to Siri, Spoken Content, Rating for Hearing Aids: M3, T4, System Requirements: Apple ID (Required For Some Features), Internet Access, Syncing to a Mac or PC Requires: macOS Catalina 10.15 or Later Using the Finder, macOS High Sierra 10.13 to macOS Mojave 10.14.6 Using iTunes 12.9 or Later, Windows 10 or Later Using iTunes 12.12.10 or Later (Free Download From itunes.com/uk)" },

    { id: 8, name: "Apple iPhone 16 Pro (128 GB, 256 GB, 512 GB)", category: "16",price: "1,49,900", imageUrl: 'images/16.1.png', des: "Titanium Design, Ceramic Shield Front, Textured Matt Glass Back, Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC standard 60529, New 16 Core Neural Engine, Enabled by TrueDepth Camera for Facial Recognition, Apple Pay, Emergency SOS via Satellite, Crash Detection, 5G (sub 6 GHz) with 4x4 MIMO, Gigabit LTE with 4x4 MIMO and LAA, 2x2 MIMO, Second Generation Ultra Wideband Chip, Thread Networking Technology, NFC with Reader Mode, Express Cards with Power Reserve, FaceTime Video Calling Over Wi Fi or a Mobile Network, FaceTime HD (1080p) Video Calling Over 5G or Wi Fi, Share Experiences Like Movies, TV, Music and Other Apps in a FaceTime Call With SharePlay, Screen Sharing, Portrait Mode in FaceTime Video, Spatial Audio, Voice Isolation and Wide Spectrum Microphone Modes, Optical Zoom with Rear Facing Camera, FaceTime Audio, Voice Over LTE (VoLTE), Wi Fi Calling, Spatial Audio Playback, User Configurable Maximum Volume Limit, Supported Formats Include HEVC, H.264 and ProRes, HDR with Dolby Vision, HDR10 and HLG, Upto 4K HDR AirPlay for Mirroring, Photos and Video Out to Apple TV (2nd Generation or Later) or AirPlay Enabled Smart TV, Video Mirroring and Video Out Support: Upto 4K HDR Through Native DisplayPort Output Over USB-C or USB-C Digital AV Adapter (Model A2119, Adapter Sold Separately), USB C Connector with Support For: Charging, DisplayPort, USB 3 (Upto 10Gb/s), Built-in Rechargeable Lithium ion Battery, MagSafe Wireless Charging Upto 15W, Qi wireless Charging Upto 7.5W, Fast Charge Capable: Upto 50% Charge in around 30 Minutes, With 20W Adapter or Higher (Available Separately), MagSafe: Magnet Array, Alignment Magnet, Accessory Identification NFC, Magnetometer, Accessibility: VoiceOver, Zoom, Magnifier, Voice Control, Switch Control, AssistiveTouch, RTT and Textphone Support, Closed Captions, Live Captions, Personal Voice, Live Speech, Type to Siri, Spoken Content, Rating for Hearing Aids: M3, T4, System Requirements: Apple ID (Required For Some Features), Internet Access, Syncing to a Mac or PC Requires: macOS Catalina 10.15 or Later Using the Finder, macOS High Sierra 10.13 to macOS Mojave 10.14.6 Using iTunes 12.9 or Later, Windows 10 or Later Using iTunes 12.12.10 or Later (Free Download From itunes.com/uk)" },

    { id: 9, name: "Apple iPhone 13 Pro Max (128 GB, 256 GB, 512 GB)", category: "13", price: "1,79,900", imageUrl: 'images/13promax.1.png', des: "Pro 12MP Camera System (Telephoto, Wide and Ultra Wide), Telephoto: f/2.8 Aperture, Wide: f/1.5 Aperture, Ultra Wide: f/1.8 Aperture, 120 Degree FOV, 3x Optical Zoom In, 2x Optical Zoom out, 6x Optical Zoom Range, Digital Zoom up to 15x, Night Mode Portraits Enabled by LiDAR Scanner, Portrait Mode with Advanced Bokeh and Depth Control, Portrait Lighting with Six Effects (Natural, Studio, Contour, Stage, Stage Mono, High Key Mono), Dual Optical Image Stabilisation (Telephoto and Wide), Sensor shift Optical Image Stabilisation (Wide), Six element Lens (Telephoto and Ultra Wide), Seven element Lens (Wide), Panorama (up to 63MP), 100% Focus Pixels (Wide), Night Mode, Deep Fusion, Smart HDR 4, Photographic Styles, Macro Photography, Apple ProRAW, Wide Colour Capture for Photos and Live Photos, Lens Correction (Ultra Wide), Advanced Red-eye Correction, Photo Geotagging, Auto Image Stabilisation, Burst Mode, Image Formats Captured: HEIF and JPEG"},

    { id: 10, name: "Apple iPhone 14 Pro Max (128 GB, 256 GB, 512 GB)", category: "14", price: "1,57,999",  imageUrl: 'images/14promax.1.png', des: " Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC Standard 60529, 16 Core Neural Engine, Enabled by TrueDepth Camera for Facial Recognition, Emergency SOS, Crash Detection, Digital Compass, Wi-Fi, Cellular, iBeacon Micro-Location, FaceTime Video Calling Over Cellular or Wi-Fi, FaceTime HD (1080p) Video Calling Over 5G or Wi-Fi, Share Experiences Like Movies, TV, Music and Other Apps in a FaceTime Call with SharePlay, Screen Sharing, Portrait Mode in FaceTime Video, Spatial Audio, Voice Isolation and Wide Spectrum, Microphone Modes, Zoom with Rear-Facing Camera, FaceTime Audio, Voice over LTE (VoLTE), Wi-Fi Calling, Spatial Audio Playback, User Configurable Maximum Volume Limit, HDR with Dolby Vision, HDR10 and HLG Upto 4K HDR AirPlay for Mirroring, Photos and Video Out to Apple TV (2nd generation or later) or AirPlay 2 Enabled Smart TV, Video Mirroring and Video Out Support: Upto 1080p Through Lightning Digital AV Adapter and Lightning to VGA Adapter (Adapters Sold Separately), MagSafe Wireless Charging Upto 15 W, Qi Wireless Charging Upto 7.5 W, Charging via USB to Computer System or Power Adapter, Magnet Array, Voice Control, Voice Over, Zoom, Magnifier, RTT and TTY Support, Siri and Dictation, Type to Siri, Switch Control, Closed Captions, Assistive Touch, Spoken Content, Back Tap, Alignment Magnet, Accessory Identification NFC, Magnetometer, System Requirement: Apple ID (Required for Some Features), Internet Access, Syncing to a Mac or PC Requires: macOS Catalina 10.15 or Later Using the Finder, macOS El Capitan 10.11.6 Through macOS Mojave 10.14.6 Using iTunes 12.8 or Later, Windows 7 or Later Using iTunes 12.10.10 or Later (Free Download from apple.com/in/itunes/download), Rating for Hearing Aids: M3, T4" },

    { id: 11, name: "Apple iPhone 15 Pro Max (128 GB, 256 GB, 512 GB)", category: "15", price: "1,26,999",imageUrl: 'images/15promax.1.png', des: "Titanium Design, Ceramic Shield Front, Textured Matt Glass Back, Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC standard 60529, New 16 Core Neural Engine, Enabled by TrueDepth Camera for Facial Recognition, Apple Pay, Emergency SOS via Satellite, Crash Detection, 5G (sub 6 GHz) with 4x4 MIMO, Gigabit LTE with 4x4 MIMO and LAA, 2x2 MIMO, Second Generation Ultra Wideband Chip, Thread Networking Technology, NFC with Reader Mode, Express Cards with Power Reserve, FaceTime Video Calling Over Wi Fi or a Mobile Network, FaceTime HD (1080p) Video Calling Over 5G or Wi Fi, Share Experiences Like Movies, TV, Music and Other Apps in a FaceTime Call With SharePlay, Screen Sharing, Portrait Mode in FaceTime Video, Spatial Audio, Voice Isolation and Wide Spectrum Microphone Modes, Optical Zoom with Rear Facing Camera, FaceTime Audio, Voice Over LTE (VoLTE), Wi Fi Calling, Spatial Audio Playback, User Configurable Maximum Volume Limit, Supported Formats Include HEVC, H.264 and ProRes, HDR with Dolby Vision, HDR10 and HLG, Upto 4K HDR AirPlay for Mirroring, Photos and Video Out to Apple TV (2nd Generation or Later) or AirPlay Enabled Smart TV, Video Mirroring and Video Out Support: Upto 4K HDR Through Native DisplayPort Output Over USB-C or USB-C Digital AV Adapter (Model A2119, Adapter Sold Separately), USB C Connector with Support For: Charging, DisplayPort, USB 3 (Upto 10Gb/s), Built-in Rechargeable Lithium ion Battery, MagSafe Wireless Charging Upto 15W, Qi wireless Charging Upto 7.5W, Fast Charge Capable: Upto 50% Charge in around 30 Minutes, With 20W Adapter or Higher (Available Separately), MagSafe: Magnet Array, Alignment Magnet, Accessory Identification NFC, Magnetometer, Accessibility: VoiceOver, Zoom, Magnifier, Voice Control, Switch Control, AssistiveTouch, RTT and Textphone Support, Closed Captions, Live Captions, Personal Voice, Live Speech, Type to Siri, Spoken Content, Rating for Hearing Aids: M3, T4, System Requirements: Apple ID (Required For Some Features), Internet Access, Syncing to a Mac or PC Requires: macOS Catalina 10.15 or Later Using the Finder, macOS High Sierra 10.13 to macOS Mojave 10.14.6 Using iTunes 12.9 or Later, Windows 10 or Later Using iTunes 12.12.10 or Later (Free Download From itunes.com/uk)" },

    { id: 12, name: "Apple iPhone 16 Pro Max (128 GB, 256 GB, 512 GB)", category: "16", price: "1,84,900",imageUrl: 'images/15promax.1.png', des: "Titanium Design, Ceramic Shield Front, Textured Matt Glass Back, Rated IP68 (Maximum Depth of 6 Metres Upto 30 Minutes) Under IEC standard 60529, New 16 Core Neural Engine, Enabled by TrueDepth Camera for Facial Recognition, Apple Pay, Emergency SOS via Satellite, Crash Detection, 5G (sub 6 GHz) with 4x4 MIMO, Gigabit LTE with 4x4 MIMO and LAA, 2x2 MIMO, Second Generation Ultra Wideband Chip, Thread Networking Technology, NFC with Reader Mode, Express Cards with Power Reserve, FaceTime Video Calling Over Wi Fi or a Mobile Network, FaceTime HD (1080p) Video Calling Over 5G or Wi Fi, Share Experiences Like Movies, TV, Music and Other Apps in a FaceTime Call With SharePlay, Screen Sharing, Portrait Mode in FaceTime Video, Spatial Audio, Voice Isolation and Wide Spectrum Microphone Modes, Optical Zoom with Rear Facing Camera, FaceTime Audio, Voice Over LTE (VoLTE), Wi Fi Calling, Spatial Audio Playback, User Configurable Maximum Volume Limit, Supported Formats Include HEVC, H.264 and ProRes, HDR with Dolby Vision, HDR10 and HLG, Upto 4K HDR AirPlay for Mirroring, Photos and Video Out to Apple TV (2nd Generation or Later) or AirPlay Enabled Smart TV, Video Mirroring and Video Out Support: Upto 4K HDR Through Native DisplayPort Output Over USB-C or USB-C Digital AV Adapter (Model A2119, Adapter Sold Separately), USB C Connector with Support For: Charging, DisplayPort, USB 3 (Upto 10Gb/s), Built-in Rechargeable Lithium ion Battery, MagSafe Wireless Charging Upto 15W, Qi wireless Charging Upto 7.5W, Fast Charge Capable: Upto 50% Charge in around 30 Minutes, With 20W Adapter or Higher (Available Separately), MagSafe: Magnet Array, Alignment Magnet, Accessory Identification NFC, Magnetometer, Accessibility: VoiceOver, Zoom, Magnifier, Voice Control, Switch Control, AssistiveTouch, RTT and Textphone Support, Closed Captions, Live Captions, Personal Voice, Live Speech, Type to Siri, Spoken Content, Rating for Hearing Aids: M3, T4, System Requirements: Apple ID (Required For Some Features), Internet Access, Syncing to a Mac or PC Requires: macOS Catalina 10.15 or Later Using the Finder, macOS High Sierra 10.13 to macOS Mojave 10.14.6 Using iTunes 12.9 or Later, Windows 10 or Later Using iTunes 12.12.10 or Later (Free Download From itunes.com/uk)" },
  ];

  function addProducts(displayProducts){
    const productList = document.getElementById("product-list");
    productList.innerHTML = "";

    displayProducts.forEach(product => {
        const productItem = document.createElement("div");
        productItem.classList.add("product-item");
        productItem.innerHTML = `
        <img src="${product.imageUrl}" alt="${product.name}">
      <h3>${product.name}</h3>
      <button class="kick"> Kick Deal </button>
      <div class= "pri">
        <p class="price">Rs. ${product.price}</p>
      </div>
      <button class="get" onclick="showProductDetails(${product.id})">Get Info</button>
        `

        productList.appendChild(productItem);
    })
  }

  
  document.addEventListener("DOMContentLoaded", () => {
    addProducts(products);
  });

  function showProductDetails(productId) {
    const selectedProduct = products.find(product => product.id === productId);
    
    // Save product details to localStorage
    localStorage.setItem('selectedProduct', JSON.stringify(selectedProduct));
  
    // Redirect to product details page
    window.location.href = 'productdetails.html';
  }
  

  // Function to filter products by category

  function filterProducts(category){
    let filteredProducts = [];

    if(category === "all"){
        filteredProducts = products;
    }  else {
        filteredProducts = products.filter(product => product.category === category);
    }

    addProducts(filteredProducts);
  }

  document.getElementById("video").volume = 0.3;
document.getElementById("audio").volume = 10.0;


